version: "3.8"
services:
  mongo:
    image: mongo:latest
    container_name: sorteo-api-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: sorteo-api-db
    networks:
      - app-network

  node:
    build: .
    container_name: sorteo-api
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      MONGO_URI: mongodb://root:example@mongo:27017/sorteo-api-db?authSource=admin
    depends_on:
      - mongo
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
